# GitHub Pages configuration
title: "Symphony Layers Interactive Explorer"
description: "Interactive tool for exploring Symphony marine spatial planning data layers"
url: "https://github.com/Mistra-C2B2/Symphony-Layers-Interactive-Explorer"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - node_modules/
  - package*.json
  - README.md
  - .gitignore

# Include data files
include:
  - data/